import time

import scrapy

from imdb_spider.items import ImdbSpiderItem


class ImdbSpider(scrapy.Spider):
    name = 'imdb'
    # allowed_domains = ['imdb.com/']
    # start_urls = ['https://www.imdb.com/chart/top/?ref_=nv_mv_250/']
    start_urls = [
        'https://www.imdb.com/title/tt0111161/reviews/',
        'https://www.imdb.com/title/tt0068646/reviews/',
        'https://www.imdb.com/title/tt0071562/reviews/',
        'https://www.imdb.com/title/tt0468569/reviews/',
        'https://www.imdb.com/title/tt0050083/reviews/',
        'https://www.imdb.com/title/tt0108052/reviews/',
        'https://www.imdb.com/title/tt0167260/reviews/',
        'https://www.imdb.com/title/tt0110912/reviews/',
        'https://www.imdb.com/title/tt0060196/reviews/',
        'https://www.imdb.com/title/tt0120737/reviews/',
        'https://www.imdb.com/title/tt0137523/reviews/',
        'https://www.imdb.com/title/tt0109830/reviews/',
        'https://www.imdb.com/title/tt1375666/reviews/',
        'https://www.imdb.com/title/tt0167261/reviews/',
        'https://www.imdb.com/title/tt0080684/reviews/',
        'https://www.imdb.com/title/tt0133093/reviews/',
        'https://www.imdb.com/title/tt0099685/reviews/',
        'https://www.imdb.com/title/tt0073486/reviews/',
        'https://www.imdb.com/title/tt0047478/reviews/',
        'https://www.imdb.com/title/tt0114369/reviews/',
        'https://www.imdb.com/title/tt0102926/reviews/',
        'https://www.imdb.com/title/tt0317248/reviews/',
        'https://www.imdb.com/title/tt0038650/reviews/',
        'https://www.imdb.com/title/tt0118799/reviews/',
        'https://www.imdb.com/title/tt0076759/reviews/',
        'https://www.imdb.com/title/tt0120815/reviews/',
        'https://www.imdb.com/title/tt0245429/reviews/',
        'https://www.imdb.com/title/tt0816692/reviews/',
        'https://www.imdb.com/title/tt0120689/reviews/',
        'https://www.imdb.com/title/tt6751668/reviews/',
        'https://www.imdb.com/title/tt0110413/reviews/',
        'https://www.imdb.com/title/tt0056058/reviews/',
        'https://www.imdb.com/title/tt0114814/reviews/',
        'https://www.imdb.com/title/tt0253474/reviews/',
        'https://www.imdb.com/title/tt0088763/reviews/',
        'https://www.imdb.com/title/tt0103064/reviews/',
        'https://www.imdb.com/title/tt0027977/reviews/',
        'https://www.imdb.com/title/tt0054215/reviews/',
        'https://www.imdb.com/title/tt0110357/reviews/',
        'https://www.imdb.com/title/tt0120586/reviews/',
        'https://www.imdb.com/title/tt0021749/reviews/',
        'https://www.imdb.com/title/tt0172495/reviews/',
        'https://www.imdb.com/title/tt2582802/reviews/',
        'https://www.imdb.com/title/tt0407887/reviews/',
        'https://www.imdb.com/title/tt0095327/reviews/',
        'https://www.imdb.com/title/tt1675434/reviews/',
        'https://www.imdb.com/title/tt0482571/reviews/',
        'https://www.imdb.com/title/tt0034583/reviews/',
        'https://www.imdb.com/title/tt0064116/reviews/',
        'https://www.imdb.com/title/tt0047396/reviews/',
        'https://www.imdb.com/title/tt0095765/reviews/',
        'https://www.imdb.com/title/tt0078748/reviews/',
        'https://www.imdb.com/title/tt0078788/reviews/',
        'https://www.imdb.com/title/tt0209144/reviews/',
        'https://www.imdb.com/title/tt0082971/reviews/',
        'https://www.imdb.com/title/tt0032553/reviews/',
        'https://www.imdb.com/title/tt0405094/reviews/',
        'https://www.imdb.com/title/tt1853728/reviews/',
        'https://www.imdb.com/title/tt0050825/reviews/',
        'https://www.imdb.com/title/tt0043014/reviews/',
        'https://www.imdb.com/title/tt0910970/reviews/',
        'https://www.imdb.com/title/tt0081505/reviews/',
        'https://www.imdb.com/title/tt0051201/reviews/',
        'https://www.imdb.com/title/tt4154756/reviews/',
        'https://www.imdb.com/title/tt7286456/reviews/',
        'https://www.imdb.com/title/tt0057012/reviews/',
        'https://www.imdb.com/title/tt4633694/reviews/',
        'https://www.imdb.com/title/tt0364569/reviews/',
        'https://www.imdb.com/title/tt0119698/reviews/',
        'https://www.imdb.com/title/tt8503618/reviews/',
        'https://www.imdb.com/title/tt0087843/reviews/',
        'https://www.imdb.com/title/tt5311514/reviews/',
        'https://www.imdb.com/title/tt1345836/reviews/',
        'https://www.imdb.com/title/tt0090605/reviews/',
        'https://www.imdb.com/title/tt2380307/reviews/',
        'https://www.imdb.com/title/tt0048473/reviews/',
        'https://www.imdb.com/title/tt0082096/reviews/',
        'https://www.imdb.com/title/tt8267604/reviews/',
        'https://www.imdb.com/title/tt0057565/reviews/',
        'https://www.imdb.com/title/tt4154796/reviews/',
        'https://www.imdb.com/title/tt0169547/reviews/',
        'https://www.imdb.com/title/tt0114709/reviews/',
        'https://www.imdb.com/title/tt0112573/reviews/',
        'https://www.imdb.com/title/tt0086879/reviews/',
        'https://www.imdb.com/title/tt1187043/reviews/',
        'https://www.imdb.com/title/tt0361748/reviews/',
        'https://www.imdb.com/title/tt0119217/reviews/',
        'https://www.imdb.com/title/tt0086190/reviews/',
        'https://www.imdb.com/title/tt0062622/reviews/',
        'https://www.imdb.com/title/tt0105236/reviews/',
        'https://www.imdb.com/title/tt0022100/reviews/',
        'https://www.imdb.com/title/tt0986264/reviews/',
        'https://www.imdb.com/title/tt0033467/reviews/',
        'https://www.imdb.com/title/tt0052357/reviews/',
        'https://www.imdb.com/title/tt0180093/reviews/',
        'https://www.imdb.com/title/tt2106476/reviews/',
        'https://www.imdb.com/title/tt0091251/reviews/',
        'https://www.imdb.com/title/tt0045152/reviews/',
        'https://www.imdb.com/title/tt0053125/reviews/',
        'https://www.imdb.com/title/tt0338013/reviews/',
        'https://www.imdb.com/title/tt0040522/reviews/',
        'https://www.imdb.com/title/tt0044741/reviews/',
        'https://www.imdb.com/title/tt0056172/reviews/',
        'https://www.imdb.com/title/tt0012349/reviews/',
        'https://www.imdb.com/title/tt10272386/reviews/',
        'https://www.imdb.com/title/tt0093058/reviews/',
        'https://www.imdb.com/title/tt5074352/reviews/',
        'https://www.imdb.com/title/tt0066921/reviews/',
        'https://www.imdb.com/title/tt0075314/reviews/',
        'https://www.imdb.com/title/tt0017136/reviews/',
        'https://www.imdb.com/title/tt0070735/reviews/',
        'https://www.imdb.com/title/tt0036775/reviews/',
        'https://www.imdb.com/title/tt8579674/reviews/',
        'https://www.imdb.com/title/tt0053604/reviews/',
        'https://www.imdb.com/title/tt1832382/reviews/',
        'https://www.imdb.com/title/tt0211915/reviews/',
        'https://www.imdb.com/title/tt1255953/reviews/',
        'https://www.imdb.com/title/tt0208092/reviews/',
        'https://www.imdb.com/title/tt0086250/reviews/',
        'https://www.imdb.com/title/tt0435761/reviews/',
        'https://www.imdb.com/title/tt0056592/reviews/',
        'https://www.imdb.com/title/tt0059578/reviews/',
        'https://www.imdb.com/title/tt1049413/reviews/',
        'https://www.imdb.com/title/tt0097576/reviews/',
        'https://www.imdb.com/title/tt0119488/reviews/',
        'https://www.imdb.com/title/tt0113277/reviews/',
        'https://www.imdb.com/title/tt0042876/reviews/',
        'https://www.imdb.com/title/tt0055630/reviews/',
        'https://www.imdb.com/title/tt0089881/reviews/',
        'https://www.imdb.com/title/tt0095016/reviews/',
        'https://www.imdb.com/title/tt0071853/reviews/',
        'https://www.imdb.com/title/tt6966692/reviews/',
        'https://www.imdb.com/title/tt0363163/reviews/',
        'https://www.imdb.com/title/tt0372784/reviews/',
        'https://www.imdb.com/title/tt0053291/reviews/',
        'https://www.imdb.com/title/tt0042192/reviews/',
        'https://www.imdb.com/title/tt0105695/reviews/',
        'https://www.imdb.com/title/tt0118849/reviews/',
        'https://www.imdb.com/title/tt0347149/reviews/',
        'https://www.imdb.com/title/tt0993846/reviews/',
        'https://www.imdb.com/title/tt0057115/reviews/',
        'https://www.imdb.com/title/tt0055031/reviews/',
        'https://www.imdb.com/title/tt0112641/reviews/',
        'https://www.imdb.com/title/tt0040897/reviews/',
        'https://www.imdb.com/title/tt0457430/reviews/',
        'https://www.imdb.com/title/tt0469494/reviews/',
        'https://www.imdb.com/title/tt0268978/reviews/',
        'https://www.imdb.com/title/tt1305806/reviews/',
        'https://www.imdb.com/title/tt0081398/reviews/',
        'https://www.imdb.com/title/tt0096283/reviews/',
        'https://www.imdb.com/title/tt0071315/reviews/',
        'https://www.imdb.com/title/tt0120735/reviews/',
        'https://www.imdb.com/title/tt0015864/reviews/',
        'https://www.imdb.com/title/tt5027774/reviews/',
        'https://www.imdb.com/title/tt0046912/reviews/',
        'https://www.imdb.com/title/tt0477348/reviews/',
        'https://www.imdb.com/title/tt1130884/reviews/',
        'https://www.imdb.com/title/tt0050976/reviews/',
        'https://www.imdb.com/title/tt0080678/reviews/',
        'https://www.imdb.com/title/tt0084787/reviews/',
        'https://www.imdb.com/title/tt0167404/reviews/',
        'https://www.imdb.com/title/tt2096673/reviews/',
        'https://www.imdb.com/title/tt0434409/reviews/',
        'https://www.imdb.com/title/tt4729430/reviews/',
        'https://www.imdb.com/title/tt0041959/reviews/',
        'https://www.imdb.com/title/tt0083658/reviews/',
        'https://www.imdb.com/title/tt0050986/reviews/',
        'https://www.imdb.com/title/tt0050212/reviews/',
        'https://www.imdb.com/title/tt0117951/reviews/',
        'https://www.imdb.com/title/tt0476735/reviews/',
        'https://www.imdb.com/title/tt0120382/reviews/',
        'https://www.imdb.com/title/tt0107290/reviews/',
        'https://www.imdb.com/title/tt1291584/reviews/',
        'https://www.imdb.com/title/tt0116282/reviews/',
        'https://www.imdb.com/title/tt0353969/reviews/',
        'https://www.imdb.com/title/tt0266543/reviews/',
        'https://www.imdb.com/title/tt0031381/reviews/',
        'https://www.imdb.com/title/tt0046438/reviews/',
        'https://www.imdb.com/title/tt0266697/reviews/',
        'https://www.imdb.com/title/tt0047296/reviews/',
        'https://www.imdb.com/title/tt0079944/reviews/',
        'https://www.imdb.com/title/tt0017925/reviews/',
        'https://www.imdb.com/title/tt0077416/reviews/',
        'https://www.imdb.com/title/tt3011894/reviews/',
        'https://www.imdb.com/title/tt1205489/reviews/',
        'https://www.imdb.com/title/tt0015324/reviews/',
        'https://www.imdb.com/title/tt3170832/reviews/',
        'https://www.imdb.com/title/tt2278388/reviews/',
        'https://www.imdb.com/title/tt0112471/reviews/',
        'https://www.imdb.com/title/tt0060827/reviews/',
        'https://www.imdb.com/title/tt0978762/reviews/',
        'https://www.imdb.com/title/tt0107207/reviews/',
        'https://www.imdb.com/title/tt1392214/reviews/',
        'https://www.imdb.com/title/tt0031679/reviews/',
        'https://www.imdb.com/title/tt2267998/reviews/',
        'https://www.imdb.com/title/tt0264464/reviews/',
        'https://www.imdb.com/title/tt0035446/reviews/',
        'https://www.imdb.com/title/tt2119532/reviews/',
        'https://www.imdb.com/title/tt8108198/reviews/',
        'https://www.imdb.com/title/tt0072684/reviews/',
        'https://www.imdb.com/title/tt0118715/reviews/',
        'https://www.imdb.com/title/tt1950186/reviews/',
        'https://www.imdb.com/title/tt2024544/reviews/',
        'https://www.imdb.com/title/tt0019254/reviews/',
        'https://www.imdb.com/title/tt0892769/reviews/',
        'https://www.imdb.com/title/tt1392190/reviews/',
        'https://www.imdb.com/title/tt0046268/reviews/',
        'https://www.imdb.com/title/tt0052618/reviews/',
        'https://www.imdb.com/title/tt0405159/reviews/',
        'https://www.imdb.com/title/tt0097165/reviews/',
        'https://www.imdb.com/title/tt0074958/reviews/',
        'https://www.imdb.com/title/tt0092005/reviews/',
        'https://www.imdb.com/title/tt1201607/reviews/',
        'https://www.imdb.com/title/tt0077711/reviews/',
        'https://www.imdb.com/title/tt0061512/reviews/',
        'https://www.imdb.com/title/tt0053198/reviews/',
        'https://www.imdb.com/title/tt4016934/reviews/',
        'https://www.imdb.com/title/tt0116231/reviews/',
        'https://www.imdb.com/title/tt3315342/reviews/',
        'https://www.imdb.com/title/tt0091763/reviews/',
        'https://www.imdb.com/title/tt1028532/reviews/',
        'https://www.imdb.com/title/tt0113247/reviews/',
        'https://www.imdb.com/title/tt0079470/reviews/',
        'https://www.imdb.com/title/tt1895587/reviews/',
        'https://www.imdb.com/title/tt0395169/reviews/',
        'https://www.imdb.com/title/tt0758758/reviews/',
        'https://www.imdb.com/title/tt1979320/reviews/',
        'https://www.imdb.com/title/tt0032976/reviews/',
        'https://www.imdb.com/title/tt0060107/reviews/',
        'https://www.imdb.com/title/tt0198781/reviews/',
        'https://www.imdb.com/title/tt12361178/reviews/',
        'https://www.imdb.com/title/tt0245712/reviews/',
        'https://www.imdb.com/title/tt7060344/reviews/',
        'https://www.imdb.com/title/tt0075148/reviews/',
        'https://www.imdb.com/title/tt1954470/reviews/',
        'https://www.imdb.com/title/tt5323662/reviews/',
        'https://www.imdb.com/title/tt0118694/reviews/',
        'https://www.imdb.com/title/tt0025316/reviews/',
        'https://www.imdb.com/title/tt0087544/reviews/',
        'https://www.imdb.com/title/tt0058946/reviews/',
        'https://www.imdb.com/title/tt0381681/reviews/',
        'https://www.imdb.com/title/tt0048021/reviews/',
        'https://www.imdb.com/title/tt2948372/reviews/',
        'https://www.imdb.com/title/tt0093779/reviews/',
        'https://www.imdb.com/title/tt0083922/reviews/',
        'https://www.imdb.com/title/tt0111495/reviews/',
        'https://www.imdb.com/title/tt0018455/reviews/',
        'https://www.imdb.com/title/tt0169858/reviews/',
        'https://www.imdb.com/title/tt3417422/reviews/',
        'https://www.imdb.com/title/tt10431500/reviews/',
    ]


    def parse(self, response):
        # movie_grade = response.xpath("//span[@class='AggregateRatingButton__RatingScore-sc-1il8omz-1 fhMjqK']/text()").extract()[0]
        # movie_name = response.xpath("//h1[1]/text()").extract()[0]
        # movie_gross = response.xpath("//ul[@class='ipc-metadata-list ipc-metadata-list--dividers-none ipc-metadata-list--compact BoxOffice__MetaDataListBoxOffice-sc-40s2pl-0 fxZYqi ipc-metadata-list--base']/li[4]/div/ul/li/span/text()").extract()
        #
        # if not movie_gross:
        #     try:
        #         movie_gross = response.xpath("//ul[@class='ipc-metadata-list ipc-metadata-list--dividers-none ipc-metadata-list--compact BoxOffice__MetaDataListBoxOffice-sc-40s2pl-0 fxZYqi ipc-metadata-list--base']/li/div/ul/li/span/text()").extract()
        #     except:
        #         print(response)
        # movie = ImdbSpiderItem()
        # movie['movie_grade'] = movie_grade
        # movie['movie_name'] = movie_name
        # movie['movie_gross'] = movie_gross[0]
        # print(movie_grade + " " + movie_name + " " + movie_gross[0])
        # yield movie

        # # movielists = response.xpath("//tbody[@class='rl_lister-list']/tr")
        # # movielists = response.xpath("//tbody[@class='lister-list']/tr")
        movie_name = response.xpath('//div[@class="parent"]/h3/a/text()').extract()[0]
        movielists = response.xpath("//div[@class='lister-list']/div[@class='lister-item mode-detail imdb-user-review  collapsable']")
        for movielist in movielists:
        #     # 中文
        #     # movie_url = 'https://www.imdb.com' + movielist.xpath('./td[@class="rl_name"]/a/@href').extract()[0]
        #     # movie_name = movielist.xpath('./td[@class="rl_name"]/a/@title').extract()[0]
        #     # movie_grade = movielist.xpath('./td[@class="rl_grade_IMDB"]/span/text()').extract()[0]
        #     # movie = ImdbSpiderItem()
        #     # movie['movie_url'] = movie_url
        #     # movie['movie_name'] = movie_name
        #     # movie['movie_grade'] = movie_grade
        #     # yield movie
        #
        #     # movie_url = 'https://www.imdb.com' + movielist.xpath('./td[@class="titleColumn"]/a/@href').extract()[0]
        #     # movie_name = movielist.xpath('./td[@class="titleColumn"]/a/text()').extract()[0]
        #     # movie_grade = movielist.xpath('./td[@class="ratingColumn imdbRating"]/strong/text()').extract()[0]
            review_title = movielist.xpath('./div[@class="review-container"]/div[@class="lister-item-content"]/a/text()').extract()[0]
            review = movielist.xpath('./div[@class="review-container"]/div[@class="lister-item-content"]/div[@class="content"]/div[@class="text show-more__control"]/text()').extract()[0]
            movie = ImdbSpiderItem()
        #     # movie['movie_url'] = movie_url
            movie['movie_name'] = movie_name
            movie['review_title'] = review_title
            movie['review'] = review
        #     # movie['movie_grade'] = movie_grade
            yield movie
# class ImdbSpider(scrapy.Spider):
#     name = 'imdb'
    # start_urls = [
    #     'https://www.imdb.com/search/title/?genres=history&start=1&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=51&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=951&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1001&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1051&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=1951&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2001&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2051&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=2951&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3001&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3051&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=3951&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4001&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4051&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=4951&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5001&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5051&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=5951&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6001&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6051&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=6951&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7001&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7051&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=7951&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8001&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8051&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=8951&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9001&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9051&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9101&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9151&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9201&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9251&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9301&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9351&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9401&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9451&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9501&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9551&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9601&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9651&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9701&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9751&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9801&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9851&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9901&explore=title_type,genres&ref_=adv_prv',
    #     'https://www.imdb.com/search/title/?genres=history&start=9951&explore=title_type,genres&ref_=adv_prv'
    # ]



    # def parse(self, response):
    #     movielists = response.xpath("//div[@class='lister-list']/div[@class='lister-item mode-advanced']")
    #     for movielist in movielists:
    #         movie_name = movielist.xpath('./div[@class="lister-item-content"]/h3/a/text()').extract()[0]
    #         movie_time = movielist.xpath('./div[@class="lister-item-content"]/h3/span[@class="lister-item-year text-muted unbold"]/text()').extract()
    #         movie_genres = movielist.xpath('./div[@class="lister-item-content"]/p/span[@class="genre"]/text()').extract()[0]
    #
    #         movie = ImdbSpiderItem()
    #         movie['movie_name'] = movie_name
    #         movie['movie_time'] = movie_time
    #         movie['movie_genres'] = movie_genres
    #         yield movie